services:
  validation:
    build: .  # This will now look for the file named 'Dockerfile'
    volumes:
      - .:/app 
    environment:
      - PYTHONUNBUFFERED=1
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASS=${MQTT_PASS}
    networks:
      - kafka-pipeline
    restart: always

networks:
  kafka-pipeline:
    external: true
    name: kafka_cluster_kafka-net